# Generated by Django 4.2.9 on 2026-03-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "room_code",
                    models.CharField(
                        max_length=6, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Aguardando jogadores"),
                            ("playing", "Em andamento"),
                            ("finished", "Finalizada"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("game_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
